import type { Metadata } from "next";
import { Cairo, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer";
import { Directions, Languages } from "@/lib/types";
import Header from "./_components/header";
import { Locale } from "@/i18n.config";
import getTrans from "@/lib/translation";
import { ROUTES } from "./_components/conistant/enum";
export async function generateStaticParams() {
  return [{ locale: Languages.ARABIC }, { locale: Languages.ENGLISH }];
}
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;

  const { navbar } = await getTrans(locale);
  const links = [
    { id: 1, title: navbar.home, url: ROUTES.HOME },
    { id: 2, title: navbar.plants, url: ROUTES.PLANTS },
    { id: 3, title: navbar.stands, url: ROUTES.STANDS },
    { id: 4, title: navbar.categories, url: ROUTES.CATEGORIES },
    { id: 5, title: navbar.contact, url: ROUTES.CONTACT },
  ];

  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body
        className={
          locale === Languages.ARABIC ? cairo.className : roboto.className
        }
      >
        <Header links={links} />
        <main className="min-h-screen-90 mt-28">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
